version: '3'
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  myapp:
    build: .
    networks:
      - mynetwork
    depends_on:
      - sonarqube
    command: ["dotnet", "MyApp.dll"]
    restart: "no"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonar_net
    volumes:
      - sonar_db:/var/lib/postgresql

networks:
  mynetwork:

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
